---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wanggang.
--- DateTime: 2019/7/16 16:35
--- 引导流程：先关闭后打开
--- 流程事件：打开界面、点击按钮
--- 触发条件：任务、等级、功能点
--- 注意点：新手引导肯定是在当前点击消息发送回收到之后才去完成的，
---         如果有消息交互的话（比如升级：肯定是升级成功之后才会完成升级的引导而不是点击升级就完成了）。

---@class TutManager
TutManager = {
    tutId = 0;          -- 当前引导流程
    tutSubId = 0;       -- 当前引导流程步骤
    tutNextId = 0;      -- 当前引导流程完成后将要触发的引导流程
    tutNextSubId = 0;   -- 当前引导流程完成后将要触发的引导流程步骤

    receiveBindMsg = 0; -- 有一些引导需要收到服务器的消息才会完成
};

local _M = TutManager;

-- region 流程控制
-- 开启新手引导步骤
function _M:OpenTut(tutId,subTutId)
    if tutId == 0 then
        return;
    end
    if self.tutId == tutId and self.subTutId == subTutId then
        return;
    end

    self.tutId = tutId;
    self.subTutId = subTutId;
    self.tutInfo = self:GetTutInfo();
    -- 是否需要注册绑定时间 绑定的目的是 有些新手引导需要根据绑定消息的返回来完成
    if self.tutInfo.receiveBindMsg then 
        RegisterMessage(self.tutInfo.receiveBindMsg,self.ReceiveBindMessage);
    end
    -- 显示
    UIManager:Open(nil,UIConst.UIPanel_Tut);
end

-- 结束新手引导步骤
function _M:EndTut(tutId,subTutId)
    if self.tutId == 0 then 
        return;
    end
    
    if self.tutId ~= tutId or self.subTutId ~= subTutId then 
        return;
    end

    -- 是否是关键引导，关键引导完成之后这个引导就完成了，如果还有后续的引导，只是展示作用。
    if self.tutInfo.key == 1 then 
        -- 给服务器发送完成消息
        TutData:SendTutEnd(self.tutId);
    end

    self.tutId = 0;
    self.subTutId = 0;
    self.tutInfo = nil;
    self:ClearTut();
    if self.tutNextId == 0 then
        self:CloseTut();
    end
end

-- 数据初始化
function _M:Init()
    self:InitTutConfig();
    self:InitRegisterEvent();
end

-- 清理新手引导步骤
-- 并未关闭新手引导界面，因为后面还有后续的步骤
function _M:ClearTut()
    UIManager:GetViewCollect(UIConst.UIPanel_Tut):ClearTut();
end
-- 关闭新手引导界面
function _M:CloseTut()
    UIManager:Close(UIConst.UIPanel_Tut,true);
end

-- 存在将要做的引导
function _M:GetCanDoTutByView(viewName)
    -- 获取当前页面的新手引导
    -- 可能不止一个，取优先级最高的一个，order越小优先级越高
    local candoTutId = 0;
    local candoTutSubId = 0;
    local candoOrder = 100000;
    local tutList = self.tutConfig[viewName];
    if tutList then
        for i, tutInfo in ipairs(tutList) do
            local tutId = tutInfo.tutId;
            -- 可以做的引导
            if TutData:IsCando(tutId) then
                -- 获取优先级最高的一个引导（order越小优先级越高）
                if tutInfo.order < candoOrder then
                    candoTutId = tutId;
                    candoTutSubId = tutInfo.tutSubId;
                end
            end
        end
    end
    return candoTutId,candoTutSubId;
end

function _M:GetTutInfo(tutId,subTutId)
    for viewName, tutInfoList in pairs(self.tutConfig) do
        for i, tutInfo in ipairs(tutInfoList) do
            if tutInfo.tutId == tutId and tutInfo.subTutId == subTutId then
                return tutInfo;
            end
        end
    end
    return nil;
end
-- endregion

-- region 配置
-- TODO 新手引导的配置数据 后期使用表格
function _M:InitTutConfig()
    self.tutConfig = {
        [UIConst.UIPanel_Main] = {
            {viewName = UIConst.UIPanel_Main,tutId=1000,tutSubId=1,tutNextId=1000,tutNextSubId=2,order=1,path="main/singleButton"},
            -- {tutId=1001,tutSubId=1,tutNextId=1001,tutNextSubId=2,order=2,path="main/familyButton"},
        },
        [UIConst.UIPanel_Father] = {
            {viewName = UIConst.UIPanel_Father,tutId=1000,tutSubId=2,tutNextId=0,tutNextSubId=0,order=1,path="main/grid/001",key=1,receiveBindMsg=MsgConst.Level_Up},
            -- {tutId=1001,tutSubId=2,tutNextId=0,tutNextSubId=0,order=2,path="main/grid/002",},
        },
    };
end
-- endregion

-- region 事件扩展
-- 注册新手引导的流程事件
function _M:InitRegisterEvent()
    RegisterMessage(MsgConst.Tut_End,function(msg) self:RefreshTutMsg(msg.tutId) end);
    RegisterMessage(MsgConst.UI_Open,function(msg) self:MessageUIOpen(msg.viewName) end);
    RegisterMessage(MsgConst.UI_Click,function(msg) self:MessageUIClick(msg.nodeName) end);
end

-- 收到新手引导绑定的消息
function _M:ReceiveBindMessage()
    if self.tutId ~= tutId then 
        return;
    end
    RemoveMessage(self.receiveBindMsg,self.ReceiveBindMessage);
    self.receiveBindMsg = 0;
    self:EnvetEndTut();
end

-- 页面打开事件
-- name：UI名称
function _M:MessageUIOpen(viewName)
    local tutId = 0;
    local subTutId = 0;
    -- 是否存在引导流程
    if self.tutNextId > 0 then
        -- 打开的页面就是新手引导需要的页面
        if self.tutInfo.viewName == viewName then
            tutId = self.tutNextId;
            subTutId = self.tutNextSubId;
        end
    else
        -- 开启新的引导
        tutId,subTutId = self:GetCanDoTutByView(viewName);
    end
    self:OpenTut(tutId,subTutId);
end

-- 点击事件
-- name：点击节点的路径
function _M:MessageUIClick(nodeName)
    if self.tutId == 0 then
        return;
    end
    local curNodeName = nil;

    if curNodeName ~= nodeName then
        return;
    end

    self:EnvetEndTut();

    -- 测试
    if self.tutInfo.receiveBindMsg ~= 0 then 
        SendMessage(BeginMessage(self.tutInfo.receiveBindMsg));
    end
end

function _M:EnvetEndTut()
    -- 根据绑定的消息来完成
    if self.receiveBindMsg ~= 0 then 
        return;
    end
    -- 完成当前步骤引导
    self:EndTut();
    -- 是否还存在下一步引导
    if self.tutNextId > 0 then
        if UIManager:GetControlScript(self.tutInfo.viewName):IsShow() then
            self:OpenTut(self.tutNextId,self.tutNextSubId);
        else
            -- 页面打开的时候会自动触发 self:MessageUIOpen 从而触发下一引导
        end
    else
        -- 如果这里还有引导A的话就错误了
        -- 修改配置让引导A衔接上一引导流程，就不会再进这里，self.tutNextId>0
    end
end
-- endregion

_M:Init();