---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wanggang.
--- DateTime: 2019/7/16 16:35
---

UIPanel_Tut = UIBaseView.New(UIConst.UIPanel_Tut);

local _M = UIPanel_Tut;

function _M:OnCreate()
    print("UIPanel_Tut OnCreate");
end

function _M:OnRegisterMessage()
    print("UIPanel_Tut OnRegisterMessage");
end

function _M:OnShow()
    print("UIPanel_Tut OnShow " .. TutManager.tutId .. "_" .. TutManager.subTutId);
end

function _M:OnClose()
    print("UIPanel_Tut OnClose");
end

function _M:OnDestory()
    print("UIPanel_Tut OnDestory");
end

function _M:ClearTut()

end