---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wanggang.
--- DateTime: 2019/7/16 16:49
---

MsgConst = {
    UI_Open = 1001,
    UI_Close = 1002,
    UI_Click = 1003,
    TutEvent_End = 2001,
};