---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wanggang.
--- DateTime: 2019/7/16 16:49
---

MsgConst = {

	S2C_Tut_End = 1,

	-----------------------------------------

    UI_Open = 1001,
    UI_Close = 1002,
    UI_Click = 1003,
    Tut_End = 2001,

    Level_Up = 10000,	-- 测试消息
};