//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class WGTestWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(WGTest), typeof(System.Object));
		L.RegFunction("New", _CreateWGTest);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("aaa", get_aaa, set_aaa);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateWGTest(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				WGTest obj = new WGTest();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: WGTest.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_aaa(IntPtr L)
	{
		try
		{
			LuaDLL.lua_pushinteger(L, WGTest.aaa);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int set_aaa(IntPtr L)
	{
		try
		{
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			WGTest.aaa = arg0;
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

